class Compliment:

    def __init__(self, dna):
        self.dna=dna
        self.dnaDict={
            "A": "T",
            "T": "A",
            "C": "G",
            "G": "C"
        }

    def buildCompliment(self):

        dnaCompliment=""

        #iterates through dna
        for c in self.dna:
            letter=self.dnaDict[c]
            dnaCompliment+=letter

        dnaCompliment=dnaCompliment[::-1]
        print(dnaCompliment)

if __name__ == '__main__':

    dna="CATTTTAGAAACACGTCGGCCGGGCGTATACAAACAGACAGCCCCAAGATACCACTGCTTGTTGCTCCCACCTGGCACGGACAACTGCTTTACCGCCTTGTTGCGGGCCTTAGCGAGGTATTAGGTAGGGGGGCTGCTAGCCTGTTCTATCCTGCGGCGTCTTACCCCATCGTATGTGTCTGTCCCAGCCAGGGGCGAAACGGTCGTCTCGCGAGATCATCGCCAGCCATTTCAGTATGTCTATCCCGATAGAAGCAATTCCGCCGATGCACTATGGCAATTATAATGCCTCAGCTGTACCCCCCCGACGGTGATTCATAGCAATCCAAGGCACGCAGGTTGGGTTATTCTGTAACTTACCTACAAGGTGATACTTCCGGGATATTTCTGATATCTGACTACGCTGCGCCTCCAAAGTGACCTCCGACGATGATGTGATCAGTCGCACGGGCGTCCCGCAGTACAGCGGGGCGTATGTAGGAGCTCGTCGAAATGTTTTCAACTGAACCCGATATCTGCGTGGTATGCCAAGGCAGGATGAGACCGTAGGCAAGTTAACATGAACAGTTTGGCTGAAATTGTGTTACTAGGTCGTGCCTGACTTGCAATACTGTAGCTAAACAGCTGGCACGGGACCGAACGCCCCTCAGGAACCGTGGTGGACGGGGTAGCTCGTTTGCCATGTGCTGTATTACAATGGCGGTGCCAAAAACCAACAGTTTGGTCGGACTTCTAGGATTGATCCTTGCAGTGACCACCTACGATGTTGATAGATATTCCACGGATATATCAAGATTAGGGCGCACGCTCCAGTTAAGAAAGTCACAGTATGTTCGACTGAGGGCGCCCTTTCAACGTTAAACGCATGTTACCCCTACAGTCGGGATACGGGCTCAAATATAAAAACAGGCTTCAGGCGCCGACGTAGGCATCCATTGCGAAGGCGGCGGTGTTGGTGGGGGTCACCT"
    comp=Compliment(dna)
    comp.buildCompliment();
